/*
 * Copyright (c) 2022-2025 Tim Savage.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.winterhavenmc.spawnstar.core.util;

/**
 * Enum with entries for all player messages in language configuration files
 */
public enum MessageId
{
	COMMAND_HELP_DESTROY,
	COMMAND_HELP_GIVE,
	COMMAND_HELP_HELP,
	COMMAND_HELP_RELOAD,
	COMMAND_HELP_STATUS,
	COMMAND_HELP_USAGE_HEADER,

	COMMAND_SUCCESS_DESTROY,
	COMMAND_SUCCESS_GIVE_SENDER,
	COMMAND_SUCCESS_GIVE_TARGET,
	COMMAND_SUCCESS_GIVE_SELF,
	COMMAND_SUCCESS_RELOAD,

	COMMAND_FAIL_INVALID_COMMAND,
	COMMAND_FAIL_INVALID_HELP,
	COMMAND_FAIL_ARGS_COUNT_OVER,
	COMMAND_FAIL_ARGS_COUNT_UNDER,
	COMMAND_FAIL_DESTROY_CONSOLE,
	COMMAND_FAIL_DESTROY_NO_MATCH,
	COMMAND_FAIL_GIVE_INVENTORY_FULL,
	COMMAND_FAIL_GIVE_PLAYER_NOT_FOUND,
	COMMAND_FAIL_GIVE_QUANTITY_INVALID,
	COMMAND_FAIL_DESTROY_PERMISSION,
	COMMAND_FAIL_GIVE_PERMISSION,
	COMMAND_FAIL_RELOAD_PERMISSION,
	COMMAND_FAIL_STATUS_PERMISSION,
	COMMAND_FAIL_HELP_PERMISSION,

	TELEPORT_SUCCESS,
	TELEPORT_FAIL_PERMISSION,
	TELEPORT_FAIL_MIN_PROXIMITY,
	TELEPORT_FAIL_SHIFT_CLICK,
	TELEPORT_FAIL_WORLD_DISABLED,
	TELEPORT_CANCELLED_DAMAGE,
	TELEPORT_CANCELLED_INTERACTION,
	TELEPORT_CANCELLED_MOVEMENT,
	TELEPORT_CANCELLED_NO_ITEM,
	TELEPORT_COOLDOWN,
	TELEPORT_WARMUP,
	TELEPORT_PLAYER_WARMING,
	TELEPORT_LOG_USAGE,

	COMMAND_STATUS_HEADER,
	COMMAND_STATUS_PLUGIN_VERSION,
	COMMAND_STATUS_LANGUAGE_SETTING,
	COMMAND_STATUS_LOCALE_SETTING,
	COMMAND_STATUS_TIMEZONE_SETTING,
	COMMAND_STATUS_DEFAULT_MATERIAL_SETTING,
	COMMAND_STATUS_MINIMUM_DISTANCE_SETTING,
	COMMAND_STATUS_TELEPORT_WARMUP_SETTING,
	COMMAND_STATUS_TELEPORT_COOLDOWN_SETTING,
	COMMAND_STATUS_SHIFT_CLICK_SETTING,
	COMMAND_STATUS_INVENTORY_REMOVAL_SETTING,
	COMMAND_STATUS_ENABLED_WORLDS_SETTING,
	COMMAND_STATUS_ALLOW_IN_RECIPES_SETTING,
	COMMAND_STATUS_DISPLAY_LIGHTNING_SETTING,
	COMMAND_STATUS_CANCEL_ON_DAMAGE_SETTING,
	COMMAND_STATUS_CANCEL_ON_MOVEMENT_SETTING,
	COMMAND_STATUS_CANCEL_ON_INTERACTION_SETTING,
	COMMAND_STATUS_FOOTER,
}
